---
resources:
  - name: landscape
    type: git
    source:
      uri: {{landscape-git-repo}}
      branch: {{landscape-git-repo-branch}}
      paths: [cf-abacus,abacus-config]
      private_key: {{landscape-git-repo-private-key}}
      skip-ssl-verification: true

jobs:
  - name: abacus-setup
    serial_groups: [abacus-deploy]
    plan:
      - get: landscape
        trigger: true

      - task: setup-abacus-infra
        attempts: 2
        timeout: 35m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: godofcontainers/ubuntu-14.04-cf
              tag: 14.04
          inputs:
            - name: landscape
          params:
            CF_SYS_DOMAIN: {{cf-sys-domain}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-user}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
            CREATE_DB_SERVICE: {{create-db-service}}
            DB_SERVICE_NAME: {{db-service-name}}
            DB_SERVICE_INSTANCES: {{db-service-instances}}
            DB_COLLECTOR: {{db-collector}}
            DB_METER: {{db-meter}}
            DB_ACCUMULATOR: {{db-accumulator}}
            DB_AGGREGATOR: {{db-aggregator}}
            DB_BRIDGE: {{db-bridge}}
            DB_PLUGINS: {{db-plugins}}
            ENABLE_SERVICE_ACCESS: {{enable-service-access}}
            UAA_ADMIN: {{uaa-admin}}
            UAA_SECRET: {{uaa-secret}}
            SYSTEM_CLIENT_ID: {{system-client-id}}
            SYSTEM_CLIENT_SECRET: {{system-client-secret}}
            CC_CLIENT_ID: {{cc-client-id}}
            CC_CLIENT_SECRET: {{cc-client-secret}}
            BRIDGE_CLIENT_ID: {{bridge-client-id}}
            BRIDGE_CLIENT_SECRET: {{bridge-client-secret}}
            CF_CLIENT_ID: {{cf-client-id}}
            CF_CLIENT_SECRET: {{cf-client-secret}}
            CONTAINER_CLIENT_ID: {{container-client-id}}
            CONTAINER_CLIENT_SECRET: {{container-client-secret}}
            OBJECT_STORAGE_CLIENT_ID: {{object-storage-client-id}}
            OBJECT_STORAGE_CLIENT_SECRET: {{object-storage-client-secret}}
            HYSTRIX_CLIENT_ID: {{hystrix-client-id}}
            HYSTRIX_CLIENT_SECRET: {{hystrix-client-secret}
            SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
            BIND_SECURITY_GROUP: {{bind-security-group}}
          run:
            path: landscape/cf-abacus/etc/concourse/scripts/cf-deploy-infra

  - name: abacus-deploy
    serial_groups: [abacus-deploy]
    plan:
      - get: landscape
        passed: [abacus-setup]
        trigger: true

      - aggregate:
        - task: build-abacus
          timeout: 30m
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: godofcontainers/node-mongodb
                tag: 8.9.0
            inputs:
              - name: landscape
            outputs:
              - name: built-project
            run:
              path: landscape/cf-abacus/etc/concourse/scripts/cf-deploy-build
            params:
              AUTH_SERVER: {{auth-server}}
              JWTKEY: {{jwtkey}}
              JWTALGO: {{jwtalgo}}
              CONFIGURE: {{abacus-configure}}
              SYSTEM_CLIENT_ID: {{system-client-id}}
              SYSTEM_CLIENT_SECRET: {{system-client-secret}}
              BRIDGE_CLIENT_ID: {{bridge-client-id}}
              BRIDGE_CLIENT_SECRET: {{bridge-client-secret}}
              CONTAINER_CLIENT_ID: {{container-client-id}}
              CONTAINER_CLIENT_SECRET: {{container-client-secret}}
              SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
              SLACK: {{slack}}
        - task: update-uaa-clients
          timeout: 10m
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: godofcontainers/ubuntu-14.04-cf
                tag: 14.04
            inputs:
              - name: landscape
            run:
              path: landscape/cf-abacus/etc/concourse/scripts/create-uaa-clients
            params:
              CF_SYS_DOMAIN: {{cf-sys-domain}}
              UAA_ADMIN: {{uaa-admin}}
              UAA_SECRET: {{uaa-secret}}
              SYSTEM_CLIENT_ID: {{system-client-id}}
              SYSTEM_CLIENT_SECRET: {{system-client-secret}}
              CC_CLIENT_ID: {{cc-client-id}}
              CC_CLIENT_SECRET: {{cc-client-secret}}
              BRIDGE_CLIENT_ID: {{bridge-client-id}}
              BRIDGE_CLIENT_AUTHORITIES: {{bridge-client-authorities}}
              BRIDGE_CLIENT_SECRET: {{bridge-client-secret}}
              CF_CLIENT_ID: {{cf-client-id}}
              CF_CLIENT_SECRET: {{cf-client-secret}}
              CONTAINER_CLIENT_ID: {{container-client-id}}
              CONTAINER_CLIENT_SECRET: {{container-client-secret}}
              OBJECT_STORAGE_CLIENT_ID: {{object-storage-client-id}}
              OBJECT_STORAGE_CLIENT_SECRET: {{object-storage-client-secret}}
              HYSTRIX_CLIENT_ID: {{hystrix-client-id}}
              HYSTRIX_CLIENT_SECRET: {{hystrix-client-secret}}
              SKIP_SSL_VALIDATION: {{skip-ssl-validation}}

      - task: stage-abacus
        attempts: 3
        timeout: 1h
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: godofcontainers/node-mongodb
              tag: 8.9.0
          inputs:
            - name: built-project
          params:
            CF_SYS_DOMAIN: {{cf-sys-domain}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-user}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
            BIND_DB_SERVICE: {{bind-db-service}}
            ABACUS_PROFILE: {{abacus-profile}}
            BUILDPACK: {{nodejs-buildpack}}
            SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
            # Uncomment to save file handlers and offload CF stagers
            # JOBS: 2
            RESTART_RETRIES: {{restart-retries}}
            ABACUS_PREFIX: {{abacus-prefix}}
          run:
            path: built-project/etc/concourse/scripts/cf-deploy-stage

      - task: start-abacus
        attempts: 3
        timeout: 1h
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: godofcontainers/node-mongodb
              tag: 8.9.0
          inputs:
            - name: built-project
          params:
            CF_SYS_DOMAIN: {{cf-sys-domain}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-user}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
            # Uncomment to save file handlers and offload CF stagers
            # JOBS: 2
            RESTART_RETRIES: {{restart-retries}}
          run:
            path: built-project/etc/concourse/scripts/cf-deploy-start


      - task: test-abacus
        attempts: 2
        timeout: 20m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: godofcontainers/node-mongodb
              tag: 8.9.0
          inputs:
            - name: built-project
          params:
            CF_SYS_DOMAIN: {{cf-sys-domain}}
            CF_DOMAIN: {{cf-domain}}
            SECURED: true
            CLIENT_ID: {{object-storage-client-id}}
            CLIENT_SECRET: {{object-storage-client-secret}}
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
            ABACUS_PREFIX: {{abacus-prefix}}
          run:
            path: built-project/etc/concourse/scripts/cf-deploy-test
