---
resources:
  - name: landscape
    type: git
    source:
      uri: {{landscape-git-repo}}
      branch: {{landscape-git-repo-branch}}
      paths: [{{paths}}]
      private_key: {{landscape-git-repo-private-key}}
      skip-ssl-verification: true
  - name: abacus
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/cf-abacus.git
      branch: master

jobs:

################################### CF #########################################

  - name: cf-deploy
    plan:
      - aggregate:
        - get: abacus
          trigger: true
        - get: landscape
          trigger: true
      - task: infra
        attempts: 2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: godofcontainers/ubuntu-14.04-cf
              tag: 14.04
          inputs:
            - name: abacus
          params:
            CF_SYS_DOMAIN: {{cf-sys-domain}}
            SKIP_CREATE_USER: {{skip-create-user}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-user}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            SKIP_CREATE_ORG: {{skip-create-org}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
            DEBUG: {{debug}}
            UAA_ADMIN: {{uaa-admin}}
            UAA_SECRET: {{uaa-secret}}
            SYSTEM_CLIENT_ID: {{system-client-id}}
            SYSTEM_CLIENT_SECRET: {{system-client-secret}}
            CC_CLIENT_ID: {{cc-client-id}}
            CC_CLIENT_SECRET: {{cc-client-secret}}
            BRIDGE_CLIENT_ID: {{bridge-client-id}}
            BRIDGE_CLIENT_AUTHORITIES: {{bridge-client-authorities}}
            BRIDGE_CLIENT_SECRET: {{bridge-client-secret}}
            CF_CLIENT_ID: {{cf-client-id}}
            CF_CLIENT_SECRET: {{cf-client-secret}}
            CONTAINER_CLIENT_ID: {{container-client-id}}
            CONTAINER_CLIENT_SECRET: {{container-client-secret}}
            OBJECT_STORAGE_CLIENT_ID: {{object-storage-client-id}}
            OBJECT_STORAGE_CLIENT_SECRET: {{object-storage-client-secret}}
            HYSTRIX_CLIENT_ID: {{hystrix-client-id}}
            HYSTRIX_CLIENT_SECRET: {{hystrix-client-secret}}
            SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
          run:
            path: abacus/etc/concourse/scripts/cf-test-infra
      - task: deploy
        attempts: 2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: godofcontainers/node-mongodb
              tag: 8.9.0
          inputs:
            - name: abacus
            - name: landscape
          params:
            # Enable tests on CF (used in cftest script)
            CF_TEST: true
            # Uncomment to save file handlers and offload CF stagers
            # JOBS: 2
            # Use specific node.js buildpack to enable latest node 8
            BUILDPACK: https://github.com/cloudfoundry/nodejs-buildpack.git#v1.6.10
            # Cloud Foundry infrastructure
            CF_SYS_DOMAIN: {{cf-sys-domain}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-user}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
            DEBUG: {{debug}}
            ABACUS_PREFIX: {{abacus-prefix}}
            SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
            RESTART_RETRIES: {{restart-retries}}
            PROJECT_DIR: {{project-dir}}
            CONFIG_DIR: {{config-dir}}
          run:
            path: abacus/etc/concourse/scripts/cf-test-test
