#!/bin/bash

set -e

echo "Creating security group for CF API access ..."
group="["
for line in $(host api.$CF_SYS_DOMAIN | awk '/has address/ { print $4 }'); do
  group+="{\"protocol\":\"tcp\",\"destination\":\"$line\",\"ports\":\"80,443\"},"
done
group+="]"
echo "${group/,]/]}" > abacus-sec-group.json
cf create-security-group $CF_ORG abacus-sec-group.json
cf update-security-group $CF_ORG abacus-sec-group.json
cf bind-security-group $CF_ORG $CF_ORG $CF_SPACE
rm -f abacus-sec-group.json
