#!/bin/bash

set -e -x

echo "Environment:"
env | sort

SCRIPT_DIR="${BASH_SOURCE%/*}"
source $SCRIPT_DIR/common-functions

if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
  skip='--skip-ssl-validation'
fi

echo "Logging to $CF_SYS_DOMAIN ..."
cf login -a https://api.$CF_SYS_DOMAIN -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE $skip

echo "Pushing $ABACUS_PROFILE Abacus installation ..."
pushd built-project
  npm run cfstage -- $ABACUS_PROFILE

  collectorApps=$(node_modules/abacus-etc/apprc lib/metering/collector/.apprc $ABACUS_PROFILE APPS)
  meterApps=$(node_modules/abacus-etc/apprc lib/metering/meter/.apprc $ABACUS_PROFILE APPS)
  accumulatorApps=$(node_modules/abacus-etc/apprc lib/aggregation/accumulator/.apprc $ABACUS_PROFILE APPS)
  aggregatorApps=$(node_modules/abacus-etc/apprc lib/aggregation/aggregator/.apprc $ABACUS_PROFILE APPS)
  reportingApps=$(node_modules/abacus-etc/apprc lib/aggregation/reporting/.apprc $ABACUS_PROFILE APPS)

  echo "Mapping routes ..."
  mapRoutes ${ABACUS_PREFIX}abacus-usage-collector $collectorApps
  mapRoutes ${ABACUS_PREFIX}abacus-usage-reporting $reportingApps

  echo "Deleting obsolete apps ..."
  deleteObsoleteApps ${ABACUS_PREFIX}abacus-usage-collector $collectorApps
  deleteObsoleteApps ${ABACUS_PREFIX}abacus-usage-meter $meterApps
  deleteObsoleteApps ${ABACUS_PREFIX}abacus-usage-accumulator $accumulatorApps
  deleteObsoleteApps ${ABACUS_PREFIX}abacus-usage-aggregator $aggregatorApps
  deleteObsoleteApps ${ABACUS_PREFIX}abacus-usage-reporting $reportingApps
popd

if [ "$BIND_DB_SERVICE" == "true" ]; then
  echo "Binding services ..."
  getApps
  bindService ${ABACUS_PREFIX}abacus-usage-collector $DB_COLLECTOR
  bindService ${ABACUS_PREFIX}abacus-usage-meter $DB_METER
  bindService ${ABACUS_PREFIX}abacus-usage-accumulator $DB_ACCUMULATOR
  bindService ${ABACUS_PREFIX}abacus-usage-aggregator $DB_AGGREGATOR
  bindService ${ABACUS_PREFIX}abacus-usage-reporting $DB_AGGREGATOR,$DB_ACCUMULATOR
  bindService ${ABACUS_PREFIX}abacus-cf-bridge,${ABACUS_PREFIX}abacus-cf-renewer $DB_BRIDGE
  bindService ${ABACUS_PREFIX}abacus-provisioning-plugin,${ABACUS_PREFIX}abacus-account-plugin $DB_PLUGINS
fi
