#!/bin/bash

set -e -x

echo "Environment:"
env | sort

SCRIPT_DIR="${BASH_SOURCE%/*}"
source $SCRIPT_DIR/common-functions

if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
  skip='--skip-ssl-validation'
fi

echo "Logging to $CF_API ..."
cf login -a https://api.$CF_API -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE $skip

echo "Pushing $ABACUS_PROFILE Abacus installation ..."
pushd built-project
  npm run cfstage -- $ABACUS_PROFILE
popd

echo "Mapping routes ..."
mapRoutes ${ABACUS_PREFIX}abacus-usage-collector 6
mapRoutes ${ABACUS_PREFIX}abacus-usage-reporting 6

if [ "$BIND_DB_SERVICE" == "true" ]; then
  echo "Binding services ..."
  getApps
  bindService abacus-usage-collector $DB_COLLECTOR
  bindService abacus-usage-meter $DB_METER
  bindService abacus-usage-accumulator $DB_ACCUMULATOR
  bindService abacus-usage-aggregator $DB_AGGREGATOR
  bindService abacus-usage-reporting $DB_AGGREGATOR,$DB_ACCUMULATOR
  bindService abacus-cf-bridge,abacus-cf-renewer $DB_BRIDGE
  bindService abacus-provisioning-plugin,abacus-account-plugin $DB_PLUGINS
fi
