#!/bin/bash

set -e

SCRIPT_DIR="${BASH_SOURCE%/*}"
source $SCRIPT_DIR/common-functions

echo "Logging to $CF_SYS_DOMAIN ..."
if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
  skip='--skip-ssl-validation'
fi

cf login -a https://api.$CF_SYS_DOMAIN -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE $skip
getApps '\-old'

if [ ${#APPS[@]} -eq 0 ]; then
  echo "Found no old applications"
else
  echo "Deleting old applications: ${APPS[@]}"
  echo ${APPS[@]} | xargs -n1 -P 50 "$SCRIPT_DIR/safe-delete-app"
fi

echo "Clean-up finished"
