#!/bin/bash

set -e

pushd built-project
  yarn run smoke --collector https://${ABACUS_PREFIX}abacus-usage-collector.$CF_DOMAIN --reporting https://${ABACUS_PREFIX}abacus-usage-reporting.$CF_DOMAIN --auth-server https://api.$CF_SYS_DOMAIN --start-timeout $CI_START_TIMEOUT --total-timeout $CI_PIPELINE_TIMEOUT
popd
