#!/bin/bash

set -e -x

SCRIPT_DIR="${BASH_SOURCE%/*}"
source $SCRIPT_DIR/common-functions

if [ -e "built-project/bin/pre-start" ]; then
  echo "Running pre-start script ..."
  ./built-project/bin/pre-start
fi

echo "Logging to $CF_SYS_DOMAIN ..."
if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
  skip='--skip-ssl-validation'
fi

cf login -a https://api.$CF_SYS_DOMAIN -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE $skip
getApps

set +e
echo "Starting applications ..."
echo ${APPS[@]} | xargs -n1 -P 5 cf start

echo "Applications:"
cf apps

echo "Restarting failed apps ..."
restartAppsWithRetry

echo "Applications:"
cf apps

echo "Deploy finished"
