#!/bin/bash

set -e

echo "Environment:"
env | sort

echo "Copying Abacus ..."
cp -r landscape/cf-abacus/. built-project

abacus_config_dir="landscape/abacus-config/deploy"

if [ -e $abacus_config_dir/bin/pre-build ]; then
  $abacus_config_dir/bin/pre-build
fi

if [[ $CONFIGURE = true ]]; then
  echo "Running custom configuration ..."
  ./landscape/cf-abacus/etc/concourse/scripts/configure $abacus_config_dir
fi

echo "Copying custom settings ..."
cp -r $abacus_config_dir/. built-project

echo "Building Abacus ..."
pushd built-project
  npm run prepare
popd

echo "Done."
