#!/bin/bash
set -e -x

echo "Environment:"
env | sort

echo "Logging to $CF_API ..."
cf login --skip-ssl-validation -a https://api.$CF_API -u $CF_ADMIN_USER -p $CF_ADMIN_PASSWORD -o $CF_ORG -s $CF_SPACE

if [ -z "$ABACUS_CLIENT_ID" ] || [ -z "$ABACUS_CLIENT_SECRET" ]; then
  echo "Missing ABACUS_CLIENT_ID or ABACUS_CLIENT_SECRET !"
  exit 1
fi

AUTH_SERVER=https://uaa.$CF_API

echo "Getting token for $ABACUS_CLIENT_ID from $AUTH_SERVER ..."

TOKEN=$(curl -k --user $ABACUS_CLIENT_ID:$ABACUS_CLIENT_SECRET -s "$AUTH_SERVER/oauth/token?grant_type=client_credentials" | jq -r .access_token)
if [ "$TOKEN" == "null" ]; then
  echo "No token found ! Are your credentials correct (ABACUS_CLIENT_ID and ABACUS_CLIENT_SECRET)?"
fi
echo "Token obtained"
echo ""

for url in $(cf apps | tail -n +5 | tr -d , | awk  '{for(i=6;i<=NF;++i)print $i}' )
do
  response=$(curl -k -H "Authorization: bearer $TOKEN" -X OPTIONS --write-out "\nHTTP_CODE: %{http_code}" --silent https://$url)
  response_status=$(echo $response | sed -n -e 's/^.*HTTP_CODE: //p')
  if [ $response_status != 200 ]
  then
    failed_urls=("${failed_urls[@]}" $url)
    echo "$url returns response: \n$response.\n Test will fail!!!"
  else
    echo "$url returns status code: $response_status"
  fi
done

echo ""
if [ ${#failed_urls[@]} -gt 0 ]
then
  echo "Failed applications: ${failed_urls[@]}"
  exit 1
else
  echo "All applications returned 200 OK!"
fi
