#!/bin/bash

set -e -x

echo "Environment:"
env | sort

echo "Logging to $CF_API ..."
cf api --skip-ssl-validation https://api.$CF_API
echo "" | cf login -u $CF_ADMIN_USER -p $CF_ADMIN_PASSWORD

echo "Recreating organization and space ..."
cf delete-org -f $CF_ORG
cf create-quota $CF_ORG -m 40g -r 40
cf create-org $CF_ORG -q $CF_ORG
cf create-space $CF_SPACE -o $CF_ORG

echo "Recreating user ..."
cf delete-user -f $CF_USER
cf create-user $CF_USER $CF_PASSWORD
cf set-org-role $CF_USER $CF_ORG OrgManager
cf set-space-role $CF_USER $CF_ORG $CF_SPACE SpaceManager
cf set-space-role $CF_USER $CF_ORG $CF_SPACE SpaceDeveloper

echo ""
echo "Finished setting up infrastructure."