#!/bin/bash

set -e -x

SCRIPT_DIR="${BASH_SOURCE%/*}"

echo "Environment:"
env | sort

echo "Logging to $CF_API ..."
if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
  skip='--skip-ssl-validation'
fi

cf api $skip https://api.$CF_API
echo "" | cf login -u $CF_ADMIN_USER -p $CF_ADMIN_PASSWORD

echo "Recreating organization and space ..."
cf delete-org -f $CF_ORG
cf create-quota $CF_ORG -m 40g -i 4g -r 40 -s 1 --allow-paid-service-plans
cf create-org $CF_ORG -q $CF_ORG
cf create-space $CF_SPACE -o $CF_ORG

echo "Recreating user ..."
cf delete-user -f $CF_USER
cf create-user $CF_USER $CF_PASSWORD
cf set-org-role $CF_USER $CF_ORG OrgManager
cf set-space-role $CF_USER $CF_ORG $CF_SPACE SpaceManager
cf set-space-role $CF_USER $CF_ORG $CF_SPACE SpaceDeveloper

$SCRIPT_DIR/bind-security-group
$SCRIPT_DIR/create-uaa-clients

echo ""
echo "Finished setting up infrastructure."
