#!/bin/bash

set -e

echo "Starting CouchDB ..."
/usr/local/bin/couchdb -b

pushd built-project
  TIMEOUT=$(expr ${CI_START_TIMEOUT:-10000} / 1000)
  echo "Using start timeout of $TIMEOUT seconds"

  echo "Running demo ..."
  yarn start
  sleep $TIMEOUT
  yarn run demo --start-timeout $CI_START_TIMEOUT --total-timeout $CI_PIPELINE_TIMEOUT

  echo "Stopping Abacus ..."
  yarn stop
popd

echo "Deleting DB files ..."
/usr/local/bin/couchdb -d
set +e
pkill -9 erlang
rm -rf /var/lib/couchdb
