#!/bin/bash

set -e -x

echo "Environment:"
env | sort

echo "Starting MongoDB ..."
/etc/init.d/mongodb start

pushd built-project
  TIMEOUT=$(expr ${CI_START_TIMEOUT:-10000} / 1000)
  echo "Using start timeout of $TIMEOUT seconds"

  echo "Running the duplicate usage detection tests ..."
  npm start
  sleep $TIMEOUT
  npm run dupe -t $CI_START_TIMEOUT -x $CI_PIPELINE_TIMEOUT

  echo "Stopping Abacus ..."
  npm stop
popd

echo "Deleting DB files ..."
set +e
pkill -9 mongod
rm -rf /var/lib/mongodb