#!/bin/bash

set -e -x

echo "Environment:"
env | sort

echo "Starting MongoDB ..."
/etc/init.d/mongodb start

TIMEOUT=$(expr ${CI_START_TIMEOUT:-10000} / 1000)
echo "Sleeping $TIMEOUT seconds to allow DB to start"
sleep $TIMEOUT

pushd built-project
  echo "Running integration tests ..."
  # Based on default limits in throttle and batch processing and
  # integration test matrix, we would need 2197 (= 13 * 13 * 13)
  # usage submissions to get above 90 percent regression coverage
  npm run itest -- -o 4 -i 4 -u 4 -t $CI_START_TIMEOUT -x $CI_PIPELINE_TIMEOUT
popd

echo "Deleting DB files ..."
set +e
pkill -9 mongod
rm -rf /var/lib/mongodb