#!/bin/bash

set -e

pushd built-project
  TIMEOUT=$(expr ${CI_START_TIMEOUT:-10000} / 1000)
  echo "Using start timeout of $TIMEOUT seconds"

  echo "Running performance test without security ..."
  yarn start
  sleep $TIMEOUT
  yarn run perf -o 1 -i 1 -u 1 -t $CI_START_TIMEOUT -x $CI_PIPELINE_TIMEOUT
  yarn stop

  echo "Running performance test with security ..."
  export SECURED=true
  export JWTKEY=encode
  export JWTALGO=HS256
  yarn start
  sleep $TIMEOUT
  yarn run perf -o 4 -i 4 -u 4 -t $CI_START_TIMEOUT -x $CI_PIPELINE_TIMEOUT

  echo "Stopping Abacus ..."
  yarn stop
popd
