#!/bin/bash

set -e

pushd built-project
  TIMEOUT=$(expr ${CI_START_TIMEOUT:-10000} / 1000)
  echo "Using start timeout of $TIMEOUT seconds"

  echo "Running the duplicate usage detection tests ..."
  yarn start
  sleep $TIMEOUT
  yarn run dupe --start-timeout $CI_START_TIMEOUT --synthetic

  echo "Stopping Abacus ..."
  yarn stop
popd
